### ISSUE TITLE
Unable to parse records: KeychainRequired

### ISSUE THREAD

**Issue by ConfusedPotato21** [lvauvillier/dji-log-parser#24]
Got my API key, but can't decrypt any files. 

![Image](https://github.com/user-attachments/assets/2023cb58-96a6-4300-a700-5348338f708e)
this should be the api key, right? couldn't find anything else, and its also super unusual to get presented with an api key just like that, usually its at least hidden. Also, can this tool decrypt files extracted from Mini 2?

**Comment by lvauvillier** [comment]
Hey @ConfusedPotato21. This is already fixed (see #21). Can you try with the latest release?

**Comment by ConfusedPotato21** [comment]
![Image](https://github.com/user-attachments/assets/5443aa55-1c87-45de-adb5-130e509a69ee)

still the same thing, this is the latest release. maybe i am putting the API key wrong somehow, or this isn't it? does the format look right?

**Comment by lvauvillier** [comment]
@ConfusedPotato21 can you share the log file? I'll investigate.

**Comment by RegEM** [comment]
I get the error with Mini2 logs. 
Firmware recently upgraded.
The parser works properly with my Mini3 log files.

```
$env:RUST_BACKTRACE = "full"
.\dji-log.exe --api-key c9******0d 
..\DJIFlightRecord_2025-04-20_[14-49-28].txt 
-k ..\DJIFlightRecord_2025-04-20_[14-49-28].kml

thread 'main' panicked at dji-log-cli\src\main.rs:77:10:
Unable to parse records: KeychainRequired
stack backtrace:
   0:     0x7ff6cf65fd52 - <unknown>
   1:     0x7ff6cf5971da - <unknown>
   2:     0x7ff6cf65f248 - <unknown>
   3:     0x7ff6cf65f9b4 - <unknown>
   4:     0x7ff6cf65eea8 - <unknown>
   5:     0x7ff6cf66de2a - <unknown>
   6:     0x7ff6cf66dd7f - <unknown>
   7:     0x7ff6cf66e64e - <unknown>
   8:     0x7ff6cf6e1291 - <unknown>
   9:     0x7ff6cf6e1630 - <unknown>
  10:     0x7ff6cf53111b - <unknown>
  11:     0x7ff6cf4e0c36 - <unknown>
  12:     0x7ff6cf53cfb2 - <unknown>
  13:     0x7ff6cf6df8fc - <unknown>
  14:     0x7ffb72697374 - BaseThreadInitThunk
  15:     0x7ffb7309cc91 - RtlUserThreadStart
```

**Comment by lvauvillier** [comment]
Hi @RegEM, can you share the log file to take a look?

**Comment by RegEM** [comment]
Thanks Luc. The log has been sent to your email. I see I was a little confused in my email, as I had tried older mini-2 files too, with the same error.

**Comment by lvauvillier** [comment]
Now fixed. Also added more explicit logs and new options to manually override the value of `department` and `version` in keychains request to handle some edge cases

**Comment by RegEM** [comment]
Awesome Luc. Thanks so much.

**Comment by danidroidvx** [comment]
Hello, how did you solve this issue? what values should I use in: department and version
